In [2]:
#numpy
import numpy as np

In [4]:
#creating a numpy array from a list
arr1 = np.array([2,5.9,3,7])
print(arr1) #list into numpy array

[2.  5.9 3.  7. ]


In [5]:
#creating a 2D Numpy array
arr2 = np.array([[6,5,4,3],[7,2,1,0]])
print(arr2)

[[6 5 4 3]
 [7 2 1 0]]


In [6]:
#Finding shape of an array
print(arr2.shape) #no. of rows and colums 

(2, 4)


In [7]:
##Finding data type of an element
print(arr1.dtype) #shows the datatype 

float64


In [8]:
#create an array of zeros
zeros=np.zeros((4,3))
print(zeros) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
#create an array of ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#create array with a range of numbers
N = np.arange(2,80,10)
print(N) #creates an array from 2 to 80 with a step of 10

[ 2 12 22 32 42 52 62 72]


In [47]:
#create an array with evenly spaced values
E = np.linspace(1,10,5)
print(E) #creates 5 equally spaced numbers b/w 1 to 10

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
#re-shape an  array
print(N.reshape(4,2)) 
#reshapes a 1D array of 8 elements into a 4x2 matrix

[[ 2 12]
 [22 32]
 [42 52]
 [62 72]]


In [10]:
arr=np.arange(4).reshape(2,2)
print(arr)

[[0 1]
 [2 3]]


In [28]:
#flatten a multidimensional array
print(arr2.flatten()) #converts a muldim into 1D array

[6 5 4 3 7 2 1 0]


In [12]:
# Find max min and sum of all elements
print(arr2.max())
print(arr.min())
print(arr1.sum())

7
0
17.9


In [13]:
#Finding mean,median,sd
print(arr1.mean())
print(np.median(arr)) #There is no median attribute in numpy
print(arr2.std())

4.475
1.5
2.29128784747792


In [16]:
#slice an array
print(arr1[3:])
print(arr2[::2])

[7.]
[[6 5 4 3]]


In [17]:
#Accessing element element in a 2D array
print(arr2[0,2])
print(arr2[1,0]) #shows 2nd row,3rd column

4
7


In [105]:
#perform element-wise addition
arr3 = np.array([4,5,6,10])
arr4 = np.array([45,3,2,0])
print(arr3 + arr4) #adds  corresponding elements

[49  8  8 10]


In [106]:
#perform element-wise multiplication
print(arr3 * arr4)

[180  15  12   0]


In [18]:
#Matrix multiplication
print(np.dot(arr1,arr1))

matx1 = np.array([5,4,5])
matx2 = np.array([6,10,0])
print(matx1*matx2)
print(np.dot(matx1,matx2))

96.81
[30 40  0]
70


In [24]:
#Transpose of a matrix
print(arr2.T)

[[6 7]
 [5 2]
 [4 1]
 [3 0]]


In [23]:
#Finding unique elements in array
w = np.array([4,5,2,4,1,7,2,9,4])
print(np.unique(w))
print(np.unique(matx1))

[1 2 4 5 7 9]
[4 5]


In [35]:
#using boolean indexing
print(w[w>5])
print(arr[arr<3])

[ 0  0  0 76  0 87 90]
[7 9]
[0 1 2]


In [40]:
#replace elements based on condition
w[w<4] = 0
print(w)

h=np.array([3,2,5,76,67,87,90])
h[h<76]=1
print(h)

[4 5 0 4 0 7 0 9 4]
[ 1  1  1 76  1 87 90]


In [70]:
#Generate random integers
INTEGER = np.random.randint(19,48,10)
print(INTEGER)

[25 43 19 39 47 40 30 19 45 34]


In [88]:
#Generate random floats
FLOAT = np.random.rand(2,1)
print(FLOAT)

[[0.99459321]
 [0.20326614]]


In [92]:
#Shuffle elements of an array
np.random.shuffle(arr2)
print(arr2)

[[7 2 1 0]
 [6 5 4 3]]


In [97]:
#Sort an array
V=np.sort(INTEGER)
print(V)

[19 19 25 30 34 39 40 43 45 47]


In [108]:
#Stack array vertically and horizontally
print(np.vstack((matx1,matx2)))
print(np.hstack((matx1,matx2)))

[[ 5  4  5]
 [ 6 10  0]]
[ 5  4  5  6 10  0]


In [110]:
ver = np.array(([4,5,6],[2,8,1]))
hor = np.array(([6,7,4],[1,4,6]))
print(np.vstack(ver))
print(np.hstack((ver,hor)))

[[4 5 6]
 [2 8 1]]
[[4 5 6 6 7 4]
 [2 8 1 1 4 6]]


In [19]:
#finding correlation coefficient
print(np.corrcoef((matx2,matx1)))

[[ 1.         -0.80295507]
 [-0.80295507  1.        ]]


In [23]:
#Save and load NumPy array
saved=np.save('array.npy',arr)
loaded=np.load('array.npy')
print(loaded)

[[0 1]
 [2 3]]
